title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://soumyak4.github.io/
baseurl: "/articles"

# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts"
#     values:
#       layout: "post"
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#     values:

permalink: "/:year/:month/:day/:title/"
