title: Articles
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: ""
baseurl: "/articles"
# Specify the folders to include
include:
  - _posts
  - assets

# Enable the caching of assets
assets:
  cache: true

# Configure the markdown renderer
markdown: kramdown

permalink: "/:year/:month/:day/:title/"

# permalink: pretty

#nav_links:
#  - title: Home
#    url: "/"
#  - title: About
#    url: "/about/"

#defaults:
#  -
#    scope:
#      path: "" # empty string matches all files
#    values:
#      img: "/assets/img/default.jpg"
      
